name: CD  
on:
  push:
    branches: [ "main" ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Deploy to server
      run: ssh user@server "docker pull shivakanojia/node-app:latest && docker run -d -p 80:80 shivakanojia/node-app:latest"